# Generated by Django 4.0.4 on 2022-06-18 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosp', '0003_patient_info_remove_choose_name_delete_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_info',
            old_name='name',
            new_name='firstname',
        ),
    ]
